echo "Downloading Sequence Data from ENSEMBL"
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/acyrthosiphon_pisum/pep/Acyrthosiphon_pisum.Acyr_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/adineta_vaga/pep/Adineta_vaga.AMS_PRJEB1171_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/aedes_aegypti/pep/Aedes_aegypti.AaegL3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/amphimedon_queenslandica/pep/Amphimedon_queenslandica.Aqu1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/anopheles_darlingi/pep/Anopheles_darlingi.AdarC3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/anopheles_gambiae/pep/Anopheles_gambiae.AgamP4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/anoplophora_glabripennis/pep/Anoplophora_glabripennis.Agla_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/apis_mellifera/pep/Apis_mellifera.Amel_4.5.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/atta_cephalotes/pep/Atta_cephalotes.Attacep1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/belgica_antarctica/pep/Belgica_antarctica.ASM77530v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/bombus_impatiens/pep/Bombus_impatiens.BIMP_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/bombus_terrestris/pep/Bombus_terrestris.Bter_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/bombyx_mori/pep/Bombyx_mori.ASM15162v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/brugia_malayi/pep/Brugia_malayi.Bmal-4.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_brenneri/pep/Caenorhabditis_brenneri.C_brenneri-6.0.1b.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_briggsae/pep/Caenorhabditis_briggsae.CB4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_japonica/pep/Caenorhabditis_japonica.C_japonica-7.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_remanei/pep/Caenorhabditis_remanei.C_remanei-15.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/capitella_teleta/pep/Capitella_teleta.Capitella_teleta_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/crassostrea_gigas/pep/Crassostrea_gigas.oyster_v9.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/culex_quinquefasciatus/pep/Culex_quinquefasciatus.CpipJ2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/danaus_plexippus/pep/Danaus_plexippus.Dpv3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/daphnia_pulex/pep/Daphnia_pulex.V1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/dendroctonus_ponderosae/pep/Dendroctonus_ponderosae.DendPond_male_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_ananassae/pep/Drosophila_ananassae.dana_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_erecta/pep/Drosophila_erecta.dere_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_grimshawi/pep/Drosophila_grimshawi.dgri_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/drosophila_melanogaster/pep/Drosophila_melanogaster.BDGP6.22.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_mojavensis/pep/Drosophila_mojavensis.dmoj_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_persimilis/pep/Drosophila_persimilis.dper_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_pseudoobscura/pep/Drosophila_pseudoobscura.Dpse_3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_sechellia/pep/Drosophila_sechellia.dsec_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_simulans/pep/Drosophila_simulans.ASM75419v3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_virilis/pep/Drosophila_virilis.dvir_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_willistoni/pep/Drosophila_willistoni.dwil_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_yakuba/pep/Drosophila_yakuba.dyak_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/heliconius_melpomene/pep/Heliconius_melpomene.Hmel1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/helobdella_robusta/pep/Helobdella_robusta.Helro1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/ixodes_scapularis/pep/Ixodes_scapularis.IscaW1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lepeophtheirus_salmonis/pep/Lepeophtheirus_salmonis.LSalAtl2s.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lingula_anatina/pep/Lingula_anatina.LinAna1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/loa_loa/pep/Loa_loa.Loa_loa_V3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lottia_gigantea/pep/Lottia_gigantea.Lotgi1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lucilia_cuprina/pep/Lucilia_cuprina.ASM118794v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/mayetiola_destructor/pep/Mayetiola_destructor.Mdes_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/megaselia_scalaris/pep/Megaselia_scalaris.Msca1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/melitaea_cinxia/pep/Melitaea_cinxia.MelCinx1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/mnemiopsis_leidyi/pep/Mnemiopsis_leidyi.MneLei_Aug2011.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/nasonia_vitripennis/pep/Nasonia_vitripennis.Nvit_2.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/nematostella_vectensis/pep/Nematostella_vectensis.ASM20922v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/octopus_bimaculoides/pep/Octopus_bimaculoides.PRJNA270931.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/onchocerca_volvulus/pep/Onchocerca_volvulus.ASM49940v2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/pediculus_humanus/pep/Pediculus_humanus.PhumU2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/pristionchus_pacificus/pep/Pristionchus_pacificus.El_Paco.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/rhodnius_prolixus/pep/Rhodnius_prolixus.RproC3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/sarcoptes_scabiei/pep/Sarcoptes_scabiei.SscaA1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/schistosoma_mansoni/pep/Schistosoma_mansoni.ASM23792v2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/solenopsis_invicta/pep/Solenopsis_invicta.Si_gnG.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/stegodyphus_mimosarum/pep/Stegodyphus_mimosarum.Stegodyphus_mimosarum_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/strigamia_maritima/pep/Strigamia_maritima.Smar1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/strongylocentrotus_purpuratus/pep/Strongylocentrotus_purpuratus.Spur_3.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/strongyloides_ratti/pep/Strongyloides_ratti.S_ratti_ED321_v5_0_4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/tetranychus_urticae/pep/Tetranychus_urticae.ASM23943v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/thelohanellus_kitauei/pep/Thelohanellus_kitauei.ASM82789v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/tribolium_castaneum/pep/Tribolium_castaneum.Tcas5.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/trichinella_spiralis/pep/Trichinella_spiralis.Tspiralis1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/trichoplax_adhaerens/pep/Trichoplax_adhaerens.ASM15027v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/zootermopsis_nevadensis/pep/Zootermopsis_nevadensis.ZooNev1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/branchiostoma_lanceolatum/pep/Branchiostoma_lanceolatum.BraLan2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/caenorhabditis_elegans/pep/Caenorhabditis_elegans.WBcel235.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/culicoides_sonorensis/pep/Culicoides_sonorensis.Cson1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/daphnia_magna/pep/Daphnia_magna.daphmag2.4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/dinothrombium_tinctorium/pep/Dinothrombium_tinctorium.DtinU1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/folsomia_candida/pep/Folsomia_candida.ASM221717v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/leptotrombidium_deliense/pep/Leptotrombidium_deliense.LdelU1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/orchesella_cincta/pep/Orchesella_cincta.ASM171814v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/teleopsis_dalmanni/pep/Teleopsis_dalmanni.Tel_dalmanni_2A_v1.0.pep.all.fa.gz -a get_metazoa.log


echo "Downloading Sequence Data from Other DBs"
https://neurobase.rc.ufl.edu/pleurobrachia/downloadFasta?id=38 -O Pleurobrachia_bachei.fasta -a get_metazoa.log