echo "Downloading Sequence Data from ENSEMBL"
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/emiliania_huxleyi/pep/Emiliania_huxleyi.Emiliana_huxleyi_CCMP1516_main_genome_assembly_v1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/phytophthora_kernoviae/pep/Phytophthora_kernoviae.PhyKer238_432v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/phytophthora_kernoviae/pep/Phytophthora_kernoviae.PhyKer238_432v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/phytophthora_sojae/pep/Phytophthora_sojae.P_sojae_V3_0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/plasmodium_chabaudi/pep/Plasmodium_chabaudi.PCHAS01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/plasmodium_falciparum/pep/Plasmodium_falciparum.EPr1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/babesia_ovata_gca_002897235/pep/Babesia_ovata_gca_002897235.Bovata_7.1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/babesia_sp_xinjiang_gca_002095265/pep/Babesia_sp_xinjiang_gca_002095265.B_xinjiang1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/besnoitia_besnoiti_gca_002563875/pep/Besnoitia_besnoiti_gca_002563875.Bbes1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/cryptosporidium_meleagridis_gca_001593445/pep/Cryptosporidium_meleagridis_gca_001593445.CryMelUKMEL1-1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/cystoisospora_suis_gca_002600585/pep/Cystoisospora_suis_gca_002600585.ASM260058v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/eimeria_tenella_gca_000499545/pep/Eimeria_tenella_gca_000499545.ETH001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/hammondia_hammondi_gca_000258005/pep/Hammondia_hammondi_gca_000258005.HHA1_v02.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_falciparum_nf54_gca_002831795/pep/Plasmodium_falciparum_nf54_gca_002831795.ASM283179v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_gallinaceum_gca_900005855/pep/Plasmodium_gallinaceum_gca_900005855.PGAL8A.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_gonderi_gca_002157705/pep/Plasmodium_gonderi_gca_002157705.Pgonderi_assembly01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_knowlesi_gca_002140095/pep/Plasmodium_knowlesi_gca_002140095.PKNOHv1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_knowlesi_gca_002140095/pep/Plasmodium_knowlesi_gca_002140095.PKNOHv1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_ovale_gca_900090025/pep/Plasmodium_ovale_gca_900090025.PowCR01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_reichenowi_gca_001601855/pep/Plasmodium_reichenowi_gca_001601855.ASM160185v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_relictum_gca_900005765/pep/Plasmodium_relictum_gca_900005765.PRELSG.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_sp_drc_itaito_gca_900257145/pep/Plasmodium_sp_drc_itaito_gca_900257145.Plasmodium_billcollinsi.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/plasmodium_sp_gorilla_clade_g2_gca_900097015/pep/Plasmodium_sp_gorilla_clade_g2_gca_900097015.PADLG01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/symbiodinium_microadriaticum_gca_001939145/pep/Symbiodinium_microadriaticum_gca_001939145.ASM193914v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/theileria_orientalis_gca_003072525/pep/Theileria_orientalis_gca_003072525.ASM307252v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_ari_gca_000250965/pep/Toxoplasma_gondii_ari_gca_000250965.TGARI_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_coug_gca_000338675/pep/Toxoplasma_gondii_coug_gca_000338675.TGCOUG_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_gca_000256705/pep/Toxoplasma_gondii_gca_000256705.TGCAST_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_mas_gca_000224865/pep/Toxoplasma_gondii_mas_gca_000224865.TGMAS1_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_p89_gca_000224885/pep/Toxoplasma_gondii_p89_gca_000224885.TGP89A_v02.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_rub_gca_000224805/pep/Toxoplasma_gondii_rub_gca_000224805.TGRUB_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_tgcatprc2_gca_000256725/pep/Toxoplasma_gondii_tgcatprc2_gca_000256725.TGCATPRC2_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_alveolata1_collection/toxoplasma_gondii_vand_gca_000224845/pep/Toxoplasma_gondii_vand_gca_000224845.TGVAND_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/cavenderia_fasciculata_gca_000203815/pep/Cavenderia_fasciculata_gca_000203815.DFas_2.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/entamoeba_histolytica_hm_1_imss_a_gca_000365475/pep/Entamoeba_histolytica_hm_1_imss_a_gca_000365475.EHA_CA_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/entamoeba_histolytica_hm_1_imss_b_gca_000344925/pep/Entamoeba_histolytica_hm_1_imss_b_gca_000344925.EHA_CB_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/entamoeba_histolytica_hm_3_imss_gca_000346345/pep/Entamoeba_histolytica_hm_3_imss_gca_000346345.EHA.strHM3_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/entamoeba_histolytica_ku27_gca_000338855/pep/Entamoeba_histolytica_ku27_gca_000338855.EHA_ku27_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/entamoeba_invadens_ip1_gca_000330505/pep/Entamoeba_invadens_ip1_gca_000330505.EIA2_v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/entamoeba_nuttalli_p19_gca_000257125/pep/Entamoeba_nuttalli_p19_gca_000257125.ENU1_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/planoprotostelium_fungivorum_gca_003024175/pep/Planoprotostelium_fungivorum_gca_003024175.ASM302417v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_amoebozoa1_collection/tieghemostelium_lacteum_gca_001606155/pep/Tieghemostelium_lacteum_gca_001606155.ASM160615v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_euglenozoa1_collection/strigomonas_culicis_gca_000442495/pep/Strigomonas_culicis_gca_000442495.Strigomonas_culicis_Genome.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_euglenozoa1_collection/trypanosoma_brucei_equiperdum_gca_003543875/pep/Trypanosoma_brucei_equiperdum_gca_003543875.ASM354387v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_euglenozoa1_collection/trypanosoma_conorhini_gca_003719485/pep/Trypanosoma_conorhini_gca_003719485.ASM371948v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_euglenozoa1_collection/trypanosoma_equiperdum_gca_001457755/pep/Trypanosoma_equiperdum_gca_001457755.Trypanosoma_equiperdum_OVI_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_euglenozoa1_collection/trypanosoma_rangeli_sc58_gca_000492115/pep/Trypanosoma_rangeli_sc58_gca_000492115.T_rangeli_SC58v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_euglenozoa1_collection/trypanosoma_theileri_gca_002087225/pep/Trypanosoma_theileri_gca_002087225.Tth_v3.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_fornicata1_collection/giardia_intestinalis_gca_000498715/pep/Giardia_intestinalis_gca_000498715.ASM49871v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_fornicata1_collection/kipferlia_bialata_gca_003568945/pep/Kipferlia_bialata_gca_003568945.KIPB_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_parabasalia1_collection/tritrichomonas_foetus_gca_001839685/pep/Tritrichomonas_foetus_gca_001839685.ASM183968v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/achlya_hypogyna_gca_002081595/pep/Achlya_hypogyna_gca_002081595.ACH_lane_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/aphanomyces_astaci_gca_003666305/pep/Aphanomyces_astaci_gca_003666305.astaci_KB13.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/ectocarpus_siliculosus_gca_000310025/pep/Ectocarpus_siliculosus_gca_000310025.ASM31002v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/fragilariopsis_cylindrus_ccmp1102_gca_001750085/pep/Fragilariopsis_cylindrus_ccmp1102_gca_001750085.Fracy1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/hondaea_fermentalgiana_gca_002897355/pep/Hondaea_fermentalgiana_gca_002897355.Aurantiochytrium_FCC1311_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/nothophytophthora_sp_chile5_gca_001712635/pep/Nothophytophthora_sp_chile5_gca_001712635.PfChile5v2.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/peronospora_effusa_gca_003843895/pep/Peronospora_effusa_gca_003843895.ASM384389v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/phytophthora_cactorum_gca_003287315/pep/Phytophthora_cactorum_gca_003287315.Pcac_10300_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/phytophthora_megakarya_gca_002215365/pep/Phytophthora_megakarya_gca_002215365.ASM221536v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/phytophthora_palmivora_var_palmivora_gca_002911725/pep/Phytophthora_palmivora_var_palmivora_gca_002911725.ASM291172v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/phytophthora_parasitica_gca_000509505/pep/Phytophthora_parasitica_gca_000509505.Phyt_para_CHvinca01_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/plasmopara_halstedii_gca_900000015/pep/Plasmopara_halstedii_gca_900000015.Plasmopara_halstedii_genome.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/protists_stramenopiles1_collection/thraustotheca_clavata_gca_002081575/pep/Thraustotheca_clavata_gca_002081575.Thrcla_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/protists/release-44/fasta/toxoplasma_gondii/pep/Toxoplasma_gondii.TGA4.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/guillardia_theta/pep/Guillardia_theta.Guith1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_alveolata1_collection/babesia_microti_strain_ri/pep/Babesia_microti_strain_ri.ASM69194v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_alveolata1_collection/cryptosporidium_parvum/pep/Cryptosporidium_parvum.ASM20969v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_alveolata1_collection/eimeria_necatrix/pep/Eimeria_necatrix.ENH001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_alveolata1_collection/plasmodium_berghei_gca_900044335/pep/Plasmodium_berghei_gca_900044335.PbK173.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_alveolata1_collection/theileria_annulata/pep/Theileria_annulata.ASM322v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_alveolata1_collection/vitrella_brassicaformis_ccmp3155/pep/Vitrella_brassicaformis_ccmp3155.Vbrassicaformis.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_amoebozoa1_collection/polysphondylium_pallidum_pn500/pep/Polysphondylium_pallidum_pn500.PolPal_Dec2009.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_euglenozoa1_collection/bodo_saltans/pep/Bodo_saltans.BSAL.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_euglenozoa1_collection/leishmania_braziliensis_mhom_br_75_m2904/pep/Leishmania_braziliensis_mhom_br_75_m2904.ASM284v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_euglenozoa1_collection/leishmania_infantum_jpcm5/pep/Leishmania_infantum_jpcm5.ASM287v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_euglenozoa1_collection/leishmania_mexicana_mhom_gt_2001_u1103/pep/Leishmania_mexicana_mhom_gt_2001_u1103.ASM23466v4.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_parabasalia1_collection/trichomonas_vaginalis_g3/pep/Trichomonas_vaginalis_g3.ASM282v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_rhizaria1_collection/bigelowiella_natans_gca_000002455/pep/Bigelowiella_natans_gca_000002455.ASM245v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_rhizaria1_collection/lotharella_oceanica/pep/Lotharella_oceanica.ASM69843v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_rhizaria1_collection/paulinella_chromatophora/pep/Paulinella_chromatophora.ASM1792v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_stramenopiles1_collection/albugo_candida/pep/Albugo_candida.ASM107853v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-43/protists/fasta/protists_stramenopiles1_collection/thalassiosira_oceanica_ccmp1005/pep/Thalassiosira_oceanica_ccmp1005.ASM19663v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/albugo_laibachii/pep/Albugo_laibachii.ENA1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/bigelowiella_natans/pep/Bigelowiella_natans.Bigna1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/dictyostelium_discoideum/pep/Dictyostelium_discoideum.dicty_2.7.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/entamoeba_histolytica/pep/Entamoeba_histolytica.JCVI-ESG2-1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/giardia_lamblia/pep/Giardia_lamblia.GL2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/hyaloperonospora_arabidopsidis/pep/Hyaloperonospora_arabidopsidis.HyaAraEmoy2_2.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/leishmania_major/pep/Leishmania_major.ASM272v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/paramecium_tetraurelia/pep/Paramecium_tetraurelia.ASM16542v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/phaeodactylum_tricornutum/pep/Phaeodactylum_tricornutum.ASM15095v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/phytophthora_infestans/pep/Phytophthora_infestans.ASM14294v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/phytophthora_lateralis/pep/Phytophthora_lateralis.MPF4_v1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/phytophthora_parasitica/pep/Phytophthora_parasitica.Phyt_para_P1569_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/phytophthora_ramorum/pep/Phytophthora_ramorum.ASM14973v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/plasmodium_berghei/pep/Plasmodium_berghei.PBANKA01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/plasmodium_vivax/pep/Plasmodium_vivax.ASM241v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/babesia_bigemina_gca_000981445/pep/Babesia_bigemina_gca_000981445.Bbig001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/babesia_bovis_gca_000165395/pep/Babesia_bovis_gca_000165395.ASM16539v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/cryptosporidium_andersoni_gca_001865355/pep/Cryptosporidium_andersoni_gca_001865355.ASM186535v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/cryptosporidium_muris_rn66_gca_000006515/pep/Cryptosporidium_muris_rn66_gca_000006515.JCVI-cmg-v1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/cryptosporidium_parvum_iowa_ii_gca_000165345/pep/Cryptosporidium_parvum_iowa_ii_gca_000165345.ASM16534v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/cryptosporidium_ubiquitum_gca_001865345/pep/Cryptosporidium_ubiquitum_gca_001865345.ASM186534v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/cyclospora_cayetanensis_gca_000769155/pep/Cyclospora_cayetanensis_gca_000769155.ASM76915v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/eimeria_acervulina_gca_000499425/pep/Eimeria_acervulina_gca_000499425.EAH001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/eimeria_brunetti_gca_000499725/pep/Eimeria_brunetti_gca_000499725.EBH001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/eimeria_maxima_gca_000499605/pep/Eimeria_maxima_gca_000499605.EMW001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/eimeria_mitis_gca_000499745/pep/Eimeria_mitis_gca_000499745.EMH001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/eimeria_praecox_gca_000499445/pep/Eimeria_praecox_gca_000499445.EPH001.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/gregarina_niphandrodes_gca_000223845/pep/Gregarina_niphandrodes_gca_000223845.GNI3.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/ichthyophthirius_multifiliis_gca_000220395/pep/Ichthyophthirius_multifiliis_gca_000220395.JCVI-IMG1-V.1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/oxytricha_trifallax_gca_000295675_gca_000295675/pep/Oxytricha_trifallax_gca_000295675_gca_000295675.oxytricha_asm_v1.1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/perkinsus_marinus_atcc_50983_gca_000006405/pep/Perkinsus_marinus_atcc_50983_gca_000006405.JCVI_PMG_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_coatneyi_gca_001680005/pep/Plasmodium_coatneyi_gca_001680005.ASM168000v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_cynomolgi_strain_b_gca_000321355/pep/Plasmodium_cynomolgi_strain_b_gca_000321355.PcynB_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_7g8_gca_000150435/pep/Plasmodium_falciparum_7g8_gca_000150435.Plas_falc_7G8_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_camp_malaysia_gca_000521115/pep/Plasmodium_falciparum_camp_malaysia_gca_000521115.Plas_falc_Malayan_Camp_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_dd2_gca_000149795/pep/Plasmodium_falciparum_dd2_gca_000149795.ASM14979v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_fch_4_gca_000521155/pep/Plasmodium_falciparum_fch_4_gca_000521155.Plas_falc_FCH_4_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_hb3_gca_000149665/pep/Plasmodium_falciparum_hb3_gca_000149665.ASM14966v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_igh_cr14_gca_000186055/pep/Plasmodium_falciparum_igh_cr14_gca_000186055.ASM18605v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_malips096_e11_gca_000521035/pep/Plasmodium_falciparum_malips096_e11_gca_000521035.Plas_falc_MaliPS096_E11_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_nf135_5_c10_gca_000521075/pep/Plasmodium_falciparum_nf135_5_c10_gca_000521075.Plas_falc_NF135_5_C10_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_palo_alto_uganda_gca_000521095/pep/Plasmodium_falciparum_palo_alto_uganda_gca_000521095.Plas_falc_Uganda_Palo-Alto_FUP_H_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_raj116_gca_000186025/pep/Plasmodium_falciparum_raj116_gca_000186025.ASM18602v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_santa_lucia_gca_000150455/pep/Plasmodium_falciparum_santa_lucia_gca_000150455.Plas_falc_Santa_Lucia_Salvador_I_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_tanzania_2000708__gca_000521055/pep/Plasmodium_falciparum_tanzania_2000708__gca_000521055.Plas_falc_02000708_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_ugt5_1_gca_000401715/pep/Plasmodium_falciparum_ugt5_1_gca_000401715.Plas_falc_5_1_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_falciparum_vietnam_oak_knoll_fvo__gca_000521015/pep/Plasmodium_falciparum_vietnam_oak_knoll_fvo__gca_000521015.Plas_falc_Vietnam_Oak-Knoll_FVO_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_fragile_gca_000956335/pep/Plasmodium_fragile_gca_000956335.Plas_frag_nilgiri_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_gaboni_gca_001602025/pep/Plasmodium_gaboni_gca_001602025.ASM160202v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_inui_san_antonio_1_gca_000524495/pep/Plasmodium_inui_san_antonio_1_gca_000524495.Plas_inui_San_Antonio_1_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_malariae_gca_900088575/pep/Plasmodium_malariae_gca_900088575.Pmal.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_ovale_curtisi_gca_900088555/pep/Plasmodium_ovale_curtisi_gca_900088555.Poc1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_ovale_wallikeri_gca_900088545/pep/Plasmodium_ovale_wallikeri_gca_900088545.Pow2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_vinckei_petteri_gca_000524515/pep/Plasmodium_vinckei_petteri_gca_000524515.Plas_vinc_pett_CR_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_vinckei_vinckei_gca_000709005/pep/Plasmodium_vinckei_vinckei_gca_000709005.Plas_vinc_vinckei_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_vivax_brazil_i_gca_000320645/pep/Plasmodium_vivax_brazil_i_gca_000320645.PV_Brazil_I_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_vivax_india_vii_gca_000320625/pep/Plasmodium_vivax_india_vii_gca_000320625.PV_India_VII_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_vivax_mauritania_i_gca_000320665/pep/Plasmodium_vivax_mauritania_i_gca_000320665.PV_Mauritania_I_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_vivax_north_korean_gca_000320685/pep/Plasmodium_vivax_north_korean_gca_000320685.PV_N_Korean_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_yoelii_gca_900002385/pep/Plasmodium_yoelii_gca_900002385.PY17X01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_yoelii_17x_gca_000505035/pep/Plasmodium_yoelii_17x_gca_000505035.Plas_yoel_17X_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/plasmodium_yoelii_yoelii_gca_000003085/pep/Plasmodium_yoelii_yoelii_gca_000003085.ASM308v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/pseudocohnilembus_persalinus_gca_001447515/pep/Pseudocohnilembus_persalinus_gca_001447515.ASM144751v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/stentor_coeruleus_gca_001970955/pep/Stentor_coeruleus_gca_001970955.ASM197095v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/stylonychia_lemnae_gca_000751175/pep/Stylonychia_lemnae_gca_000751175.Stylonychia_lemnae_asm_v1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/theileria_equi_strain_wa_gca_000342415/pep/Theileria_equi_strain_wa_gca_000342415.JCVI-bewag-v1.1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/theileria_orientalis_strain_shintoku_gca_000740895/pep/Theileria_orientalis_strain_shintoku_gca_000740895.ASM74089v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/theileria_parva_gca_000165365/pep/Theileria_parva_gca_000165365.ASM16536v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/toxoplasma_gondii_fou_gca_000224905/pep/Toxoplasma_gondii_fou_gca_000224905.TGFOU1v02.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/toxoplasma_gondii_gab2_2007_gal_dom2_gca_000325525/pep/Toxoplasma_gondii_gab2_2007_gal_dom2_gca_000325525.TGGABGALDOM2_v2.1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/toxoplasma_gondii_gt1_gca_000149715/pep/Toxoplasma_gondii_gt1_gca_000149715.TGGT1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_alveolata1_collection/toxoplasma_gondii_veg_gca_000150015/pep/Toxoplasma_gondii_veg_gca_000150015.TGVEG.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_amoebozoa1_collection/acanthamoeba_castellanii_str_neff_gca_000313135/pep/Acanthamoeba_castellanii_str_neff_gca_000313135.Acastellanii.strNEFF_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_amoebozoa1_collection/dictyostelium_purpureum_gca_000190715/pep/Dictyostelium_purpureum_gca_000190715.v1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_amoebozoa1_collection/entamoeba_dispar_saw760_gca_000209125/pep/Entamoeba_dispar_saw760_gca_000209125.JCVI_EDISG_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_apusozoa1_collection/thecamonas_trahens_atcc_50062_gca_000142905/pep/Thecamonas_trahens_atcc_50062_gca_000142905.TheTra_May2010.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_apusozoa1_collection/thecamonas_trahens_atcc_50062/pep/Thecamonas_trahens_atcc_50062.TheTra_May2010.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_choanoflagellida1_collection/monosiga_brevicollis_mx1_gca_000002865/pep/Monosiga_brevicollis_mx1_gca_000002865.V1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_choanoflagellida1_collection/salpingoeca_rosetta_gca_000188695/pep/Salpingoeca_rosetta_gca_000188695.Proterospongia_sp_ATCC50818.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_cryptophyta1_collection/chroomonas_mesostigmatica_ccmp1168_gca_000286095/pep/Chroomonas_mesostigmatica_ccmp1168_gca_000286095.ASM28609v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_cryptophyta1_collection/cryptomonas_paramecium_gca_000194455/pep/Cryptomonas_paramecium_gca_000194455.ASM19445v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/angomonas_deanei_gca_000442575/pep/Angomonas_deanei_gca_000442575.Angomonas_deanei_Genome.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/leishmania_donovani_gca_000227135/pep/Leishmania_donovani_gca_000227135.ASM22713v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/leishmania_panamensis_gca_000755165/pep/Leishmania_panamensis_gca_000755165.ASM75516v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/leptomonas_pyrrhocoris_gca_001293395/pep/Leptomonas_pyrrhocoris_gca_001293395.ASM129339v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/leptomonas_seymouri_gca_001299535/pep/Leptomonas_seymouri_gca_001299535.ASM129953v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/perkinsela_sp_ccap_1560_4_gca_001235845/pep/Perkinsela_sp_ccap_1560_4_gca_001235845.ASM123584v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/phytomonas_sp_isolate_em1_gca_000582765/pep/Phytomonas_sp_isolate_em1_gca_000582765.AKH_PRJEB1535_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/phytomonas_sp_isolate_hart1_gca_000982615/pep/Phytomonas_sp_isolate_hart1_gca_000982615.AKI_PRJEB1539_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/trypanosoma_cruzi_dm28c_gca_000496795/pep/Trypanosoma_cruzi_dm28c_gca_000496795.T.cruzi.Dm28c_v01.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/trypanosoma_cruzi_marinkellei_gca_000300495/pep/Trypanosoma_cruzi_marinkellei_gca_000300495.ASM30049v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_euglenozoa1_collection/trypanosoma_rangeli_sc58_gca_000492115/pep/Trypanosoma_rangeli_sc58_gca_000492115.T_rangeli_SC58v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_fornicata1_collection/giardia_intestinalis_assemblage_b_gca_001543975/pep/Giardia_intestinalis_assemblage_b_gca_001543975.G_duodenalis_AssB_BAH15c1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_fornicata1_collection/giardia_intestinalis_atcc_50581_gca_000182405/pep/Giardia_intestinalis_atcc_50581_gca_000182405.ASM18240v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_fornicata1_collection/giardia_lamblia_p15_gca_000182665/pep/Giardia_lamblia_p15_gca_000182665.ASM18266v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_fornicata1_collection/spironucleus_salmonicida_gca_000497125/pep/Spironucleus_salmonicida_gca_000497125.SSK3.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_heterolobosea1_collection/naegleria_gruberi_gca_000004985/pep/Naegleria_gruberi_gca_000004985.V1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_ichthyosporea1_collection/capsaspora_owczarzaki_atcc_30864_gca_000151315/pep/Capsaspora_owczarzaki_atcc_30864_gca_000151315.C_owczarzaki_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_ichthyosporea1_collection/sphaeroforma_arctica_jp610_gca_001186125/pep/Sphaeroforma_arctica_jp610_gca_001186125.Spha_arctica_JP610_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_nucleariidaeandfonticulagroup1_collection/fonticula_alba_gca_000388065/pep/Fonticula_alba_gca_000388065.Font_alba_ATCC_38817_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_rhizaria1_collection/plasmodiophora_brassicae_gca_001049375/pep/Plasmodiophora_brassicae_gca_001049375.pbe3.h15.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_rhizaria1_collection/reticulomyxa_filosa_gca_000512085/pep/Reticulomyxa_filosa_gca_000512085.Reti_assembly1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/aphanomyces_invadans_gca_000520115/pep/Aphanomyces_invadans_gca_000520115.Apha_inva_NJM9701_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/aureococcus_anophagefferens_gca_000186865/pep/Aureococcus_anophagefferens_gca_000186865.v_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/blastocystis_hominis_gca_000151665/pep/Blastocystis_hominis_gca_000151665.ASM15166v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/nannochloropsis_gaditana_gca_000569095/pep/Nannochloropsis_gaditana_gca_000569095.NagaB31_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/nannochloropsis_gaditana_ccmp526_gca_000240725/pep/Nannochloropsis_gaditana_ccmp526_gca_000240725.ASM24072v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/phytophthora_nicotianae_gca_001482985/pep/Phytophthora_nicotianae_gca_001482985.ASM148298v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/phytophthora_parasitica_cj01a1_gca_000365545/pep/Phytophthora_parasitica_cj01a1_gca_000365545.Phyt_para_CJ01A1_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/phytophthora_parasitica_inra_310_gca_000247585/pep/Phytophthora_parasitica_inra_310_gca_000247585.PP_INRA-310_V2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/phytophthora_parasitica_p10297_gca_000367145/pep/Phytophthora_parasitica_p10297_gca_000367145.Phyt_para_P10297_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/phytophthora_parasitica_p1976_gca_000365525/pep/Phytophthora_parasitica_p1976_gca_000365525.Phyt_para_P1976_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/saprolegnia_diclina_vs20_gca_000281045/pep/Saprolegnia_diclina_vs20_gca_000281045.Sap_diclina_VS20_V1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/saprolegnia_parasitica_cbs_223_65_gca_000151545/pep/Saprolegnia_parasitica_cbs_223_65_gca_000151545.ASM15154v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/protists_stramenopiles1_collection/thalassiosira_oceanica_gca_000296195/pep/Thalassiosira_oceanica_gca_000296195.ThaOc_1.0.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/pythium_aphanidermatum/pep/Pythium_aphanidermatum.pag1_scaffolds_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/pythium_arrhenomanes/pep/Pythium_arrhenomanes.par_scaffolds_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/pythium_irregulare/pep/Pythium_irregulare.pir_scaffolds_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/pythium_iwayamai/pep/Pythium_iwayamai.piw_scaffolds_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/pythium_ultimum/pep/Pythium_ultimum.pug.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/pythium_vexans/pep/Pythium_vexans.pve_scaffolds_v1.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/tetrahymena_thermophila/pep/Tetrahymena_thermophila.JCVI-TTA1-2.2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/thalassiosira_pseudonana/pep/Thalassiosira_pseudonana.ASM14940v2.pep.all.fa.gz  -a get_protist.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/protists/fasta/trypanosoma_brucei/pep/Trypanosoma_brucei.TryBru_Apr2005_chr11.pep.all.fa.gz  -a get_protist.log

echo "Downloading Sequence Data from EuPathDB"
wget -nc http://amoebadb.org/common/downloads/Current_Release/EmoshkovskiiLaredo/fasta/data/AmoebaDB-44_EmoshkovskiiLaredo_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://amoebadb.org/common/downloads/Current_Release/NfowleriATCC30863/fasta/data/AmoebaDB-44_NfowleriATCC30863_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://cryptodb.org/common/downloads/Current_Release/CveliaCCMP2878/fasta/data/CryptoDB-44_CveliaCCMP2878_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://cryptodb.org/common/downloads/Current_Release/Chominis30976/fasta/data/CryptoDB-44_Chominis30976_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://cryptodb.org/common/downloads/Current_Release/ChominisTU502/fasta/data/CryptoDB-44_ChominisTU502_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://cryptodb.org/common/downloads/Current_Release/CtyzzeriUGA55/fasta/data/CryptoDB-44_CtyzzeriUGA55_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://cryptodb.org/common/downloads/Current_Release/Cubiquitum39726/fasta/data/CryptoDB-44_Cubiquitum39726_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://giardiadb.org/common/downloads/Current_Release/SsalmonicidaATCC50377/fasta/data/GiardiaDB-44_SsalmonicidaATCC50377_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://plasmodb.org/common/downloads/Current_Release/PcynomolgiM/fasta/data/PlasmoDB-44_PcynomolgiM_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://toxodb.org/common/downloads/Current_Release/NcaninumLIV/fasta/data/ToxoDB-44_NcaninumLIV_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://toxodb.org/common/downloads/Current_Release/TgondiiRH/fasta/data/ToxoDB-44_TgondiiRH_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://tritrypdb.org/common/downloads/Current_Release/LaethiopicaL147/fasta/data/TriTrypDB-44_LaethiopicaL147_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://tritrypdb.org/common/downloads/Current_Release/LtropicaL590/fasta/data/TriTrypDB-44_LtropicaL590_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://tritrypdb.org/common/downloads/Current_Release/TcongolenseIL3000/fasta/data/TriTrypDB-44_TcongolenseIL3000_AnnotatedProteins.fasta  -a get_protist.log
wget -nc http://tritrypdb.org/common/downloads/Current_Release/TvivaxY486/fasta/data/TriTrypDB-44_TvivaxY486_AnnotatedProteins.fasta  -a get_protist.log

echo "NOT Downloading Sequence Data from JGI"
#https://genome.jgi.doe.gov/portal/Aplke1/download/Aplke1_all_proteins_20121220.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Aurli1/download/Aurli1_all_proteins_20120618.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Auran1/download/proteins.Auran1_FilteredModels3.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Bigna1/download/Bigna1_all_proteins.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Crypto2293_1/download/Crypto2293_1_all_proteins_20160903.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Ochro2298_1/download/Ochro2298_1_all_proteins_20160817.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Pavlov2436_1/download/Pavlov2436_1_all_proteins_20160817.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Pelago2097_1/download/Pelago2097_1_all_proteins_20160408.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/Phyca11/download/Phyca11_unfiltered_proteins.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/portal/Phyci1/download/Phyci1_all_proteins_20120612.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/portal/Psemu1/download/Psemu1_all_proteins_20111011.aa.fasta.gz  -a get_protist.log
#https://genome.jgi.doe.gov/portal/portal/Schag1/download/Schag1_all_proteins_20121220.aa.fasta.gz  -a get_protist.log

echo "Downloading Sequence Data from Others"
wget -nc http://marinegenomics.oist.jp/symb/download/symbB.v1.2.augustus.prot.fa.gz  -a get_protist.log
wget -nc https://marinegenomics.oist.jp/symb/download/syma_aug_37.aa.gz  -a get_protist.log
wget -nc https://marinegenomics.oist.jp/symb/download/symC_aug_40.aa.gz  -a get_protist.log
wget -nc https://marinegenomics.oist.jp/ito_mozuku_v1/download/ito_mozuku_onna1_protein_seq.zip  -a get_protist.log; unzip ito_mozuku_onna1_protein_seq.zip; rm ito_mozuku_onna1_protein_seq.zip; mv ito_mozuku_onna1_protein_seq ito_mozuku_onna1_protein_seq.fasta
wget -nc https://marinegenomics.oist.jp/algae/download/160208_2k_oki_prot.fa.gz  -a get_protist.log
wget -nc https://github.com/guyleonard/blastocladiella/raw/master/run_2.all.maker.proteins.renamed.fasta  -a get_protist.log
wget -nc https://github.com/guyleonard/hyphochytrium/raw/master/data_submission/hyphochytrium_catenoides_predicted_proteins_renamed.fasta  -a get_protist.log
wget -nc http://www.ciliate.org/system/downloads/T_borealis_oct2012_proteins.fasta  -a get_protist.log
wget -nc http://www.ciliate.org/system/downloads/T_elliotti_oct2012_proteins.fasta  -a get_protist.log
wget -nc http://www.ciliate.org/system/downloads/T_malaccensis_oct2012_proteins.fasta  -a get_protist.log

echo "Downloading Sequence Data from NCBI"  -a get_protist.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/081/595/GCA_002081595.1_ACH_lane_v1/GCA_002081595.1_ACH_lane_v1_protein.faa.gz  -a get_protist.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/787/575/GCF_000787575.1_Asub_2.0/GCF_000787575.1_Asub_2.0_protein.faa.gz  -a get_protist.log
