echo "Downloading Sequence Data from ENSEMBL"
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/acyrthosiphon_pisum/pep/Acyrthosiphon_pisum.Acyr_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/adineta_vaga/pep/Adineta_vaga.AMS_PRJEB1171_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/aedes_aegypti/pep/Aedes_aegypti.AaegL3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/amphimedon_queenslandica/pep/Amphimedon_queenslandica.Aqu1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/anopheles_darlingi/pep/Anopheles_darlingi.AdarC3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/anopheles_gambiae/pep/Anopheles_gambiae.AgamP4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/anoplophora_glabripennis/pep/Anoplophora_glabripennis.Agla_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/apis_mellifera/pep/Apis_mellifera.Amel_4.5.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/atta_cephalotes/pep/Atta_cephalotes.Attacep1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/belgica_antarctica/pep/Belgica_antarctica.ASM77530v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/bombus_impatiens/pep/Bombus_impatiens.BIMP_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/bombus_terrestris/pep/Bombus_terrestris.Bter_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/bombyx_mori/pep/Bombyx_mori.ASM15162v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/brugia_malayi/pep/Brugia_malayi.Bmal-4.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_brenneri/pep/Caenorhabditis_brenneri.C_brenneri-6.0.1b.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_briggsae/pep/Caenorhabditis_briggsae.CB4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_japonica/pep/Caenorhabditis_japonica.C_japonica-7.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/caenorhabditis_remanei/pep/Caenorhabditis_remanei.C_remanei-15.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/capitella_teleta/pep/Capitella_teleta.Capitella_teleta_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/crassostrea_gigas/pep/Crassostrea_gigas.oyster_v9.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/culex_quinquefasciatus/pep/Culex_quinquefasciatus.CpipJ2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/danaus_plexippus/pep/Danaus_plexippus.Dpv3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/daphnia_pulex/pep/Daphnia_pulex.V1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/dendroctonus_ponderosae/pep/Dendroctonus_ponderosae.DendPond_male_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_ananassae/pep/Drosophila_ananassae.dana_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_erecta/pep/Drosophila_erecta.dere_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_grimshawi/pep/Drosophila_grimshawi.dgri_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/drosophila_melanogaster/pep/Drosophila_melanogaster.BDGP6.22.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_mojavensis/pep/Drosophila_mojavensis.dmoj_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_persimilis/pep/Drosophila_persimilis.dper_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_pseudoobscura/pep/Drosophila_pseudoobscura.Dpse_3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_sechellia/pep/Drosophila_sechellia.dsec_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_simulans/pep/Drosophila_simulans.ASM75419v3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_virilis/pep/Drosophila_virilis.dvir_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_willistoni/pep/Drosophila_willistoni.dwil_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/drosophila_yakuba/pep/Drosophila_yakuba.dyak_caf1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/heliconius_melpomene/pep/Heliconius_melpomene.Hmel1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/helobdella_robusta/pep/Helobdella_robusta.Helro1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/ixodes_scapularis/pep/Ixodes_scapularis.IscaW1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lepeophtheirus_salmonis/pep/Lepeophtheirus_salmonis.LSalAtl2s.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lingula_anatina/pep/Lingula_anatina.LinAna1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/loa_loa/pep/Loa_loa.Loa_loa_V3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lottia_gigantea/pep/Lottia_gigantea.Lotgi1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/lucilia_cuprina/pep/Lucilia_cuprina.ASM118794v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/mayetiola_destructor/pep/Mayetiola_destructor.Mdes_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/megaselia_scalaris/pep/Megaselia_scalaris.Msca1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/melitaea_cinxia/pep/Melitaea_cinxia.MelCinx1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/mnemiopsis_leidyi/pep/Mnemiopsis_leidyi.MneLei_Aug2011.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/nasonia_vitripennis/pep/Nasonia_vitripennis.Nvit_2.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/nematostella_vectensis/pep/Nematostella_vectensis.ASM20922v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/octopus_bimaculoides/pep/Octopus_bimaculoides.PRJNA270931.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/onchocerca_volvulus/pep/Onchocerca_volvulus.ASM49940v2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/pediculus_humanus/pep/Pediculus_humanus.PhumU2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/pristionchus_pacificus/pep/Pristionchus_pacificus.El_Paco.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/rhodnius_prolixus/pep/Rhodnius_prolixus.RproC3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/sarcoptes_scabiei/pep/Sarcoptes_scabiei.SscaA1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/schistosoma_mansoni/pep/Schistosoma_mansoni.ASM23792v2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/solenopsis_invicta/pep/Solenopsis_invicta.Si_gnG.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/stegodyphus_mimosarum/pep/Stegodyphus_mimosarum.Stegodyphus_mimosarum_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/strigamia_maritima/pep/Strigamia_maritima.Smar1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/strongylocentrotus_purpuratus/pep/Strongylocentrotus_purpuratus.Spur_3.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/strongyloides_ratti/pep/Strongyloides_ratti.S_ratti_ED321_v5_0_4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/tetranychus_urticae/pep/Tetranychus_urticae.ASM23943v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/thelohanellus_kitauei/pep/Thelohanellus_kitauei.ASM82789v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/tribolium_castaneum/pep/Tribolium_castaneum.Tcas5.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/trichinella_spiralis/pep/Trichinella_spiralis.Tspiralis1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/trichoplax_adhaerens/pep/Trichoplax_adhaerens.ASM15027v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/release-44/metazoa/fasta/zootermopsis_nevadensis/pep/Zootermopsis_nevadensis.ZooNev1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/branchiostoma_lanceolatum/pep/Branchiostoma_lanceolatum.BraLan2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/caenorhabditis_elegans/pep/Caenorhabditis_elegans.WBcel235.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/culicoides_sonorensis/pep/Culicoides_sonorensis.Cson1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/daphnia_magna/pep/Daphnia_magna.daphmag2.4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/dinothrombium_tinctorium/pep/Dinothrombium_tinctorium.DtinU1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/folsomia_candida/pep/Folsomia_candida.ASM221717v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/leptotrombidium_deliense/pep/Leptotrombidium_deliense.LdelU1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/orchesella_cincta/pep/Orchesella_cincta.ASM171814v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/fasta/teleopsis_dalmanni/pep/Teleopsis_dalmanni.Tel_dalmanni_2A_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ailuropoda_melanoleuca/pep/Ailuropoda_melanoleuca.ailMel1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/anas_platyrhynchos_platyrhynchos/pep/Anas_platyrhynchos_platyrhynchos.CAU_duck1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/anolis_carolinensis/pep/Anolis_carolinensis.AnoCar2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/aotus_nancymaae/pep/Aotus_nancymaae.Anan_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/astyanax_mexicanus/pep/Astyanax_mexicanus.Astyanax_mexicanus-2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/bos_taurus/pep/Bos_taurus.UMD3.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/callithrix_jacchus/pep/Callithrix_jacchus.ASM275486v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/canis_familiaris/pep/Canis_familiaris.CanFam3.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/capra_hircus/pep/Capra_hircus.ARS1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/carlito_syrichta/pep/Carlito_syrichta.Tarsius_syrichta-2.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cavia_aperea/pep/Cavia_aperea.CavAp1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cavia_porcellus/pep/Cavia_porcellus.Cavpor3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cebus_capucinus/pep/Cebus_capucinus.Cebus_imitator-1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cercocebus_atys/pep/Cercocebus_atys.Caty_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/chinchilla_lanigera/pep/Chinchilla_lanigera.ChiLan1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/chlorocebus_sabaeus/pep/Chlorocebus_sabaeus.ChlSab1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/choloepus_hoffmanni/pep/Choloepus_hoffmanni.choHof1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ciona_intestinalis/pep/Ciona_intestinalis.KH.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ciona_savignyi/pep/Ciona_savignyi.CSAV2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/colobus_angolensis_palliatus/pep/Colobus_angolensis_palliatus.Cang.pa_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cricetulus_griseus_crigri/pep/Cricetulus_griseus_crigri.CriGri_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/danio_rerio/pep/Danio_rerio.GRCz11.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/dasypus_novemcinctus/pep/Dasypus_novemcinctus.Dasnov3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/dipodomys_ordii/pep/Dipodomys_ordii.Dord_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/echinops_telfairi/pep/Echinops_telfairi.TENREC.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/equus_caballus/pep/Equus_caballus.EquCab3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/erinaceus_europaeus/pep/Erinaceus_europaeus.HEDGEHOG.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/felis_catus/pep/Felis_catus.Felis_catus_9.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ficedula_albicollis/pep/Ficedula_albicollis.FicAlb_1.4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/fukomys_damarensis/pep/Fukomys_damarensis.DMR_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/gadus_morhua/pep/Gadus_morhua.gadMor1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/gallus_gallus/pep/Gallus_gallus.GRCg6a.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/gasterosteus_aculeatus/pep/Gasterosteus_aculeatus.BROADS1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/gorilla_gorilla/pep/Gorilla_gorilla.gorGor4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/heterocephalus_glaber_female/pep/Heterocephalus_glaber_female.HetGla_female_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ictidomys_tridecemlineatus/pep/Ictidomys_tridecemlineatus.SpeTri2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/jaculus_jaculus/pep/Jaculus_jaculus.JacJac1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/latimeria_chalumnae/pep/Latimeria_chalumnae.LatCha1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/lepisosteus_oculatus/pep/Lepisosteus_oculatus.LepOcu1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/loxodonta_africana/pep/Loxodonta_africana.loxAfr3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/macaca_fascicularis/pep/Macaca_fascicularis.Macaca_fascicularis_5.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/macaca_mulatta/pep/Macaca_mulatta.Mmul_8.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/macaca_nemestrina/pep/Macaca_nemestrina.Mnem_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mandrillus_leucophaeus/pep/Mandrillus_leucophaeus.Mleu.le_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/meleagris_gallopavo/pep/Meleagris_gallopavo.Turkey_2.01.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mesocricetus_auratus/pep/Mesocricetus_auratus.MesAur1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/microcebus_murinus/pep/Microcebus_murinus.Mmur_3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/microtus_ochrogaster/pep/Microtus_ochrogaster.MicOch1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/monodelphis_domestica/pep/Monodelphis_domestica.monDom5.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mus_caroli/pep/Mus_caroli.CAROLI_EIJ_v1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mus_musculus/pep/Mus_musculus.GRCm38.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mus_pahari/pep/Mus_pahari.PAHARI_EIJ_v1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mus_spretus/pep/Mus_spretus.SPRET_EiJ_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mustela_putorius_furo/pep/Mustela_putorius_furo.MusPutFur1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/myotis_lucifugus/pep/Myotis_lucifugus.Myoluc2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/nannospalax_galili/pep/Nannospalax_galili.S.galili_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/nomascus_leucogenys/pep/Nomascus_leucogenys.Nleu_3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/notamacropus_eugenii/pep/Notamacropus_eugenii.Meug_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ochotona_princeps/pep/Ochotona_princeps.OchPri2.0-Ens.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/octodon_degus/pep/Octodon_degus.OctDeg1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/oreochromis_niloticus/pep/Oreochromis_niloticus.Orenil1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ornithorhynchus_anatinus/pep/Ornithorhynchus_anatinus.OANA5.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/oryctolagus_cuniculus/pep/Oryctolagus_cuniculus.OryCun2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/oryzias_latipes_hni/pep/Oryzias_latipes_hni.ASM223471v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/otolemur_garnettii/pep/Otolemur_garnettii.OtoGar3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ovis_aries/pep/Ovis_aries.Oar_v3.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pan_paniscus/pep/Pan_paniscus.panpan1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pan_troglodytes/pep/Pan_troglodytes.Pan_tro_3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/papio_anubis/pep/Papio_anubis.Panu_3.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pelodiscus_sinensis/pep/Pelodiscus_sinensis.PelSin_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/peromyscus_maniculatus_bairdii/pep/Peromyscus_maniculatus_bairdii.HU_Pman_2.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/petromyzon_marinus/pep/Petromyzon_marinus.Pmarinus_7.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/poecilia_formosa/pep/Poecilia_formosa.PoeFor_5.1.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pongo_abelii/pep/Pongo_abelii.PPYG2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/procavia_capensis/pep/Procavia_capensis.proCap1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/propithecus_coquereli/pep/Propithecus_coquereli.Pcoq_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pteropus_vampyrus/pep/Pteropus_vampyrus.pteVam1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/rattus_norvegicus/pep/Rattus_norvegicus.Rnor_6.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/rhinopithecus_bieti/pep/Rhinopithecus_bieti.ASM169854v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/rhinopithecus_roxellana/pep/Rhinopithecus_roxellana.Rrox_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/saccharomyces_cerevisiae/pep/Saccharomyces_cerevisiae.R64-1-1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/saimiri_boliviensis_boliviensis/pep/Saimiri_boliviensis_boliviensis.SaiBol1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/sarcophilus_harrisii/pep/Sarcophilus_harrisii.DEVIL7.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/sorex_araneus/pep/Sorex_araneus.COMMON_SHREW1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/sus_scrofa/pep/Sus_scrofa.Sscrofa11.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/taeniopygia_guttata/pep/Taeniopygia_guttata.taeGut3.2.4.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/takifugu_rubripes/pep/Takifugu_rubripes.FUGU5.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/tetraodon_nigroviridis/pep/Tetraodon_nigroviridis.TETRAODON8.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/tupaia_belangeri/pep/Tupaia_belangeri.TREESHREW.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/tursiops_truncatus/pep/Tursiops_truncatus.turTru1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/vicugna_pacos/pep/Vicugna_pacos.vicPac1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/xenopus_tropicalis/pep/Xenopus_tropicalis.JGI_4.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/xiphophorus_maculatus/pep/Xiphophorus_maculatus.X_maculatus-5.0-male.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/acanthochromis_polyacanthus/pep/Acanthochromis_polyacanthus.ASM210954v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/amphilophus_citrinellus/pep/Amphilophus_citrinellus.Midas_v5.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/amphiprion_ocellaris/pep/Amphiprion_ocellaris.AmpOce1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/amphiprion_percula/pep/Amphiprion_percula.Nemo_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/anabas_testudineus/pep/Anabas_testudineus.fAnaTes1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/anser_brachyrhynchus/pep/Anser_brachyrhynchus.ASM259213v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/apteryx_haastii/pep/Apteryx_haastii.aptHaa1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/apteryx_owenii/pep/Apteryx_owenii.aptOwe1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/apteryx_rowi/pep/Apteryx_rowi.aptRow1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/astatotilapia_calliptera/pep/Astatotilapia_calliptera.fAstCal1.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/bison_bison_bison/pep/Bison_bison_bison.Bison_UMD1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/bos_indicus_hybrid/pep/Bos_indicus_hybrid.UOA_Brahman_1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/bos_mutus/pep/Bos_mutus.BosGru_v2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/bos_taurus/pep/Bos_taurus.ARS-UCD1.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/calidris_pugnax/pep/Calidris_pugnax.ASM143184v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/calidris_pygmaea/pep/Calidris_pygmaea.ASM369795v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/callorhinchus_milii/pep/Callorhinchus_milii.Callorhinchus_milii-6.1.3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/canis_lupus_dingo/pep/Canis_lupus_dingo.ASM325472v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/castor_canadensis/pep/Castor_canadensis.C.can_genome_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/chelonoidis_abingdonii/pep/Chelonoidis_abingdonii.ASM359739v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/chrysemys_picta_bellii/pep/Chrysemys_picta_bellii.Chrysemys_picta_bellii-3.0.3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/coturnix_japonica/pep/Coturnix_japonica.Coturnix_japonica_2.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cricetulus_griseus_crigri/pep/Cricetulus_griseus_crigri.CriGri_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/crocodylus_porosus/pep/Crocodylus_porosus.CroPor_comp1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cyanistes_caeruleus/pep/Cyanistes_caeruleus.cyaCae2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cynoglossus_semilaevis/pep/Cynoglossus_semilaevis.Cse_v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/cyprinodon_variegatus/pep/Cyprinodon_variegatus.C_variegatus-1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/dromaius_novaehollandiae/pep/Dromaius_novaehollandiae.droNov1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/electrophorus_electricus/pep/Electrophorus_electricus.Ee_SOAP_WITH_SSPACE.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/eptatretus_burgeri/pep/Eptatretus_burgeri.Eburgeri_3.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/equus_asinus_asinus/pep/Equus_asinus_asinus.ASM303372v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/esox_lucius/pep/Esox_lucius.Eluc_V3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/fundulus_heteroclitus/pep/Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/gambusia_affinis/pep/Gambusia_affinis.ASM309773v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/gopherus_agassizii/pep/Gopherus_agassizii.ASM289641v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/haplochromis_burtoni/pep/Haplochromis_burtoni.AstBur1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/hippocampus_comes/pep/Hippocampus_comes.H_comes_QL1_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/hucho_hucho/pep/Hucho_hucho.ASM331708v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ictalurus_punctatus/pep/Ictalurus_punctatus.IpCoco_1.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/junco_hyemalis/pep/Junco_hyemalis.ASM382977v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/kryptolebias_marmoratus/pep/Kryptolebias_marmoratus.ASM164957v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/labrus_bergylta/pep/Labrus_bergylta.BallGen_V1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/lates_calcarifer/pep/Lates_calcarifer.ASB_HGAPassembly_v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/lepidothrix_coronata/pep/Lepidothrix_coronata.Lepidothrix_coronata-1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/lonchura_striata_domestica/pep/Lonchura_striata_domestica.LonStrDom1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/manacus_vitellinus/pep/Manacus_vitellinus.ASM171598v2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/marmota_marmota_marmota/pep/Marmota_marmota_marmota.marMar2.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mastacembelus_armatus/pep/Mastacembelus_armatus.fMasArm1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/maylandia_zebra/pep/Maylandia_zebra.M_zebra_UMD2a.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/melopsittacus_undulatus/pep/Melopsittacus_undulatus.Melopsittacus_undulatus_6.3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/meriones_unguiculatus/pep/Meriones_unguiculatus.MunDraft-v1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/mola_mola/pep/Mola_mola.ASM169857v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/monopterus_albus/pep/Monopterus_albus.M_albus_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/neolamprologus_brichardi/pep/Neolamprologus_brichardi.NeoBri1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/neovison_vison/pep/Neovison_vison.NNQGG.v01.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/notechis_scutatus/pep/Notechis_scutatus.TS10Xv2-PRI.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/nothoprocta_perdicaria/pep/Nothoprocta_perdicaria.notPer1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/numida_meleagris/pep/Numida_meleagris.NumMel1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/oryzias_latipes/pep/Oryzias_latipes.ASM223467v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/oryzias_melastigma/pep/Oryzias_melastigma.Om_v0.7.RACA.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/panthera_pardus/pep/Panthera_pardus.PanPar1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/panthera_tigris_altaica/pep/Panthera_tigris_altaica.PanTig1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/paramormyrops_kingsleyae/pep/Paramormyrops_kingsleyae.PKINGS_0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/parus_major/pep/Parus_major.Parus_major1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/periophthalmus_magnuspinnatus/pep/Periophthalmus_magnuspinnatus.PM.fa.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/phascolarctos_cinereus/pep/Phascolarctos_cinereus.phaCin_unsw_v4.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/piliocolobus_tephrosceles/pep/Piliocolobus_tephrosceles.ASM277652v2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/poecilia_latipinna/pep/Poecilia_latipinna.P_latipinna-1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/poecilia_mexicana/pep/Poecilia_mexicana.P_mexicana-1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/poecilia_reticulata/pep/Poecilia_reticulata.Guppy_female_1.0_MT.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pogona_vitticeps/pep/Pogona_vitticeps.pvi1.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/prolemur_simus/pep/Prolemur_simus.Prosim_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pundamilia_nyererei/pep/Pundamilia_nyererei.PunNye1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/pygocentrus_nattereri/pep/Pygocentrus_nattereri.Pygocentrus_nattereri-1.0.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/salvator_merianae/pep/Salvator_merianae.HLtupMer3.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/scleropages_formosus/pep/Scleropages_formosus.ASM162426v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/scophthalmus_maximus/pep/Scophthalmus_maximus.ASM318616v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/serinus_canaria/pep/Serinus_canaria.SCA1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/seriola_dumerili/pep/Seriola_dumerili.Sdu_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/seriola_lalandi_dorsalis/pep/Seriola_lalandi_dorsalis.Sedor1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/spermophilus_dauricus/pep/Spermophilus_dauricus.ASM240643v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/sphenodon_punctatus/pep/Sphenodon_punctatus.ASM311381v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/stegastes_partitus/pep/Stegastes_partitus.Stegastes_partitus-1.0.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/sus_scrofa_usmarc/pep/Sus_scrofa_usmarc.USMARCv1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/theropithecus_gelada/pep/Theropithecus_gelada.Tgel_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/urocitellus_parryii/pep/Urocitellus_parryii.ASM342692v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ursus_americanus/pep/Ursus_americanus.ASM334442v1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/ursus_maritimus/pep/Ursus_maritimus.UrsMar_1.0.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/vombatus_ursinus/pep/Vombatus_ursinus.bare-nosed_wombat_genome_assembly.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/vulpes_vulpes/pep/Vulpes_vulpes.VulVul2.2.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/xiphophorus_couchianus/pep/Xiphophorus_couchianus.Xiphophorus_couchianus-4.0.1.pep.all.fa.gz -a get_metazoa.log
wget -nc ftp://ftp.ensembl.org/pub/release-97/fasta/zonotrichia_albicollis/pep/Zonotrichia_albicollis.Zonotrichia_albicollis-1.0.1.pep.all.fa.gz -a get_metazoa.log

echo "Downloading Sequence Data from NCBI"
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/004/095/GCF_000004095.1_Hydra_RP_1.0/GCF_000004095.1_Hydra_RP_1.0_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/417/965/GCF_001417965.1_Aiptasia_genome_1.1/GCF_001417965.1_Aiptasia_genome_1.1_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/222/465/GCF_000222465.1_Adig_1.1/GCF_000222465.1_Adig_1.1_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/571/385/GCF_002571385.1_Stylophora_pistillata_v1/GCF_002571385.1_Stylophora_pistillata_v1_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/605/GCF_000003605.2_Skow_1.1/GCF_000003605.2_Skow_1.1_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/949/145/GCF_001949145.1_OKI-Apl_1.0/GCF_001949145.1_OKI-Apl_1.0_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/754/855/GCA_002754855.1_ASM275485v1/GCA_002754855.1_ASM275485v1_protein.faa.gz -a get_metazoa.log
wget -nc ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/224/145/GCF_000224145.3_KH/GCF_000224145.3_KH_protein.faa.gz -a get_metazoa.log

echo "Downloading Sequence Data from Other DBs"
wget -nc https://neurobase.rc.ufl.edu/pleurobrachia/downloadFasta?id=38 -O Pleurobrachia_bachei.fasta -a get_metazoa.log
wget -nc ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100565/renilla_predicted_proteins.fasta -a get_metazoa.log
wget -nc http://octopus.unit.oist.jp/HEMIDATA/pfl.prot -a get_metazoa.log
